
      - name: Start the Docker daemon
        service: name=docker enabled=yes state=restarted
        sudo: yes
        ignore_errors: yes

      - name: Create conf and logs directories
        file:
          path={{item}}
          state=directory
          recurse=true
          owner=centos
          group=centos
          mode=0755
        ignore_errors: yes
        with_items:
          - "/var/opt/observer/conf"
          - "/var/opt/observer/logs"
          - "/var/opt/observer-netproducer/conf"
          - "/var/opt/observer-netproducer/logs"

      - name: Modify the host security context
        command: chcon -Rt svirt_sandbox_file_t /var/opt/
        ignore_errors: yes


