- hosts: localhost
  name: Launch AWS instances
  connection: local
  gather_facts: False
  roles:
    - launcher

- hosts: ec2hosts
  name: Updates hosts
  remote_user: centos
  gather_facts: False
  sudo: yes
  roles:
    - updater

- hosts: localhost
  name: Reboot hosts
  connection: local
  gather_facts: False
  roles:
    - rebooter

- hosts: ec2hosts
  name: Provision hosts
  remote_user: centos
  gather_facts: False
  sudo: yes
  roles:
    - provisioner

- hosts: localhost
  name: Terminate instances
  connection: local
  gather_facts: False
  roles:
    - terminator
