
    - name: Launch a set of instances
      ec2:
         key_name: "{{key_name}}"
         region: "{{region_name}}"
         group_id: "{{group_id}}"
         instance_type: "{{instance_type}}"
         image: "{{ami_image_id}}"
         wait: true
         exact_count: "{{instance_count}}"
         count_tag:
            Name: "AWS Playground"
         instance_tags:
            Name: "AWS Playground"
      register: ec2

    - name: Add all instance public IPs to host group
      add_host: hostname={{item.public_ip}} groups=ec2hosts
      with_items: ec2.instances

    - name: Ensure instances initialize
      wait_for:
        host={{item.public_ip}}
        port=22
        delay=75
        timeout=300
      ignore_errors: yes
      with_items: ec2.instances
