    - name: "Run script to collect all runtime data"
      ignore_errors: yes
      shell: "./pcap_parser.sh summarize {{runs_per_instance}} {{instance_type}}"
      when:
        task_type == "pcap"

    - name: "Run script to collect all runtime data"
      ignore_errors: yes
      shell: "./network_parser.sh summarize {{runs_per_instance}} {{instance_type}}"
      when:
        task_type == "network"

    - name: "Fetch analysis file from instances"
      ignore_errors: yes
      fetch: "src=/home/centos/summary-{{ analysis_filename_suffix }} dest=./{{ results_dir }}"
